---
- hosts: localhost
  become: true
  tasks:
    - name: Install apache
      apt:
        name: "apache2"
        state: "present"
      tags:
        - install
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
      tags:
        - config
    - name: Restart apache
      service:
        name: apache2
        state: restarted
      tags:
        - restart
