---
- name: Manage Apache Web Server
  hosts: target
  become: yes
  gather_facts: false
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present
      tags:
        - install

    - name: Start Apache
      service:
        name: httpd
        state: started
      tags:
        - start

    - name: Copy HTML file
      copy:
        src: /etc/ansible/index.html
        dest: /var/www/html/index.html
      tags:
        - copy

    - name: Restart Apache
      service:
        name: httpd
        state: restarted
      tags:
        - restart
    - name: Always Run Me
      debug:
        msg: "This task always runs"
      tags:
        - always

    - name: Never Run Me
      debug:
        msg: "This task never runs"
      tags:
        - never

